### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by GrEFeRFeeD** [OS-IS/ai201-belobrov#1]

**Comment by GrEFeRFeeD** [comment]
![image](https://github.com/user-attachments/assets/38d97b67-cabc-4376-99bf-c437d0e86b1a)

**Comment by GrEFeRFeeD** [comment]
![image](https://github.com/user-attachments/assets/a5f8c88c-41e6-435b-9978-3b0752bdd6b1)

**Comment by GrEFeRFeeD** [comment]
![image](https://github.com/user-attachments/assets/9b5ac918-2c2a-452a-8315-7152643d7ab7)

**Comment by GrEFeRFeeD** [comment]
![image](https://github.com/user-attachments/assets/8c709bc8-b319-49f0-8c96-87c288151039)

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
